baseURL = 'https://ajeetraina.github.io/ollama-labs/'
languageCode = 'en-us'
title = 'Ollama Labs'
theme = 'hugo-book'

# Book Theme options
[params]
  # Sets color theme: light, dark or auto.
  BookTheme = 'light'

  # Controls table of contents visibility
  BookToC = true

  # Path to logo for the book
  BookLogo = 'logo.svg'

  # Specify section of content to render as menu
  BookSection = 'docs'

  # Set source repository location.
  BookRepo = 'https://github.com/ajeetraina/ollama-labs'

  # Enable 'Edit this page' links
  BookEditPath = 'edit/main'

  # Configure the date format
  BookDateFormat = 'Jan 2, 2006'

  # Enable search
  BookSearch = true

[menu]
  [[menu.after]]
    name = "Collabnix Community"
    url = "https://collabnix.com"
    weight = 10
